### ISSUE TITLE
SAS code review

### ISSUE THREAD

**Issue by anbei95** [caojie528/Stats506_F19_Group3#5]
In terms of correctness, I don't think there's any issue at all. One of the couple things I've noticed was that for the comment on line 223, you specified some age groups but these groups didn't seem to be mentioned in the following parts. The other thing is you might want to look into the marginal effects for a more solid analysis.

Cheers,
Bei

**Comment by caojie528** [comment]
Hi Bei,

Thank you for your feedback! 

I have removed the unnecessary comment for age. I also added a line of lsmeans in proc mixed. 

Best, 
Jie
