### ISSUE TITLE
Python code review

### ISSUE THREAD

**Issue by anbei95** [caojie528/Stats506_F19_Group3#6]
I saw that a warning appeared in your script about strong multicollinearity. Since, in the SAS and R versions, the models didn't have collinearity issues, something could be going wrong there. It might turn out to be a problem related to how python works differently than the others. Also, as we all need to do, it's better to add marginal effects in your analysis.

Best,
Bei

**Comment by cali-li** [comment]
Thank you for your review! I will double-check my code and finish the last part.

Best,
Cali
